// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GOD_Deck

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label12;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Button14;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Button16;
lv_obj_t * ui_Button17;
lv_obj_t * ui_Button18;
lv_obj_t * ui_Button19;
lv_obj_t * ui_Button20;
lv_obj_t * ui_Button21;
lv_obj_t * ui_Button22;
lv_obj_t * ui_Button23;
lv_obj_t * ui_Button24;
lv_obj_t * ui_Button25;
lv_obj_t * ui_Button26;
lv_obj_t * ui_Button27;
lv_obj_t * ui_Button28;
lv_obj_t * ui_Button29;
lv_obj_t * ui_Button30;
lv_obj_t * ui_Button31;
lv_obj_t * ui_Button32;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Bar3;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Bar4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Bar5;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label3;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1885285173[1] = {&ui_img_1531840258};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
