// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GOD_Deck

#ifndef _GOD_DECK_UI_H
#define _GOD_DECK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label12;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button33(lv_event_t * e);
extern lv_obj_t * ui_Button33;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_youtube_png);    // assets/Youtube.png
LV_IMG_DECLARE(ui_img_amazon_png);    // assets/Amazon.png
LV_IMG_DECLARE(ui_img_duolingo_png);    // assets/Duolingo.png
LV_IMG_DECLARE(ui_img_spotify_png);    // assets/Spotify.png
LV_IMG_DECLARE(ui_img_discord_png);    // assets/Discord.png
LV_IMG_DECLARE(ui_img_instagram_png);    // assets/Instagram.png
LV_IMG_DECLARE(ui_img_netflix_png);    // assets/Netflix.png
LV_IMG_DECLARE(ui_img_photoshop_png);    // assets/Photoshop.png
LV_IMG_DECLARE(ui_img_whatsapp_png);    // assets/Whatsapp.png
LV_IMG_DECLARE(ui_img_vs_code_png);    // assets/VS_Code.png
LV_IMG_DECLARE(ui_img_github_png);    // assets/Github.png
LV_IMG_DECLARE(ui_img_calculator_png);    // assets/Calculator.png
LV_IMG_DECLARE(ui_img_text_extractor_png);    // assets/Text_Extractor.png
LV_IMG_DECLARE(ui_img_notion_png);    // assets/Notion.png
LV_IMG_DECLARE(ui_img_1531840258);    // assets/icons8-pomodoro-64.png
LV_IMG_DECLARE(ui_img_cut_png);    // assets/Cut.png
LV_IMG_DECLARE(ui_img_copy_png);    // assets/Copy.png
LV_IMG_DECLARE(ui_img_paste_png);    // assets/Paste.png
LV_IMG_DECLARE(ui_img_hibernate_png);    // assets/Hibernate.png
LV_IMG_DECLARE(ui_img_shutdown_png);    // assets/Shutdown.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/Home.png
LV_IMG_DECLARE(ui_img_mic_png);    // assets/Mic.png
LV_IMG_DECLARE(ui_img_mute_png);    // assets/Mute.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/Back.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
